name: foodora
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/CheckenBurger.png
  - assets/facebook.png
  - assets/google.png
  - assets/image.png
  - assets/logo.png
  - assets/twetter.png
  - assets/Vegitables.png
  - assets/zengerBurger.png
  - assets/boy.png
  - assets/checkin.png
  - assets/pizza.png
  - assets/burger.png
  - assets/bag.png
